name: Deploy Flask API with Docker on Apache

on:
  push:
    branches: [master]  # Change to 'main' if your main branch is named 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Copy files to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "rm -rf ~/krupali-rag-api && mkdir -p ~/krupali-rag-api"
        scp -r . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/krupali-rag-api

    - name: Build & Run Docker container
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
        cd ~/krupali-rag-api

        echo "API_KEY=${API_KEY}" > .env
        echo "GROQ_API_KEY=${GROQ_API_KEY}" >> .env

        docker stop rag-api || true
        docker rm rag-api || true
        docker build -t rag-api .
        docker run -d -p 5003:5000 --env-file .env --name rag-api rag-api
        EOF
      env:
        API_KEY: ${{ secrets.API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
