name: Deploy Flask API to VPS

on:
  push:
    branches:
      - master  # Change to 'main' if your branch is named 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root
          rm -rf rag-flask-api || true
          git clone https://github.com/krupali-moradiya27/rag-flask-api.git
          cd rag-flask-api

          # Set environment variables
          echo "API_KEY=${{ secrets.API_KEY }}" > .env
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env

          # Rebuild and run Docker container
          docker stop rag-api || true
          docker rm rag-api || true
          docker build -t rag-api .
          docker run -d -p 5003:5000 --env-file .env --name rag-api rag-api
